---
- name: Allow Remote Connections
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\ControlSet001\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword

- name: Allow Remote Connections With Network Level Authencation
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\ControlSet001\Control\Terminal Server\WinStations\RDP-Tcp
    name: UserAuthentication
    data: 1
    type: dword