---
- name: Disable Windows update
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    type: dword
  loop: "{{ WINDOWS_UPDATE }}"

- name: Disable Windows update service
  win_service:
    name: wuauserv 
    state: stopped
    start_mode: disabled