---
- name: Deploy journald.conf template
  template:
    src: ../templates/journald.conf/journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart systemd-journald