---
################################################################
#
# 1. OOM Killerが実行された場合、カーネルパニックを発生させる。
# 2. カーネルパニックが発生した場合、サーバを再起動させる。
#
################################################################

- name: Set OOM Killer Behavior
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: 'vm.panic_on_oom', value: '2'}
    - { name: 'kernel.panic', value: '60'}