---
- name: Disable kernel update
  ini_file:
    path_file: /etc/dnf/dnf.conf
    state: present
    section: main
    option: excludepkgs
    value: kernel* centos* xorg*
    owner: root
    group: root
    mode: 0644
    backup: yes